#!/bin/sh
#
#	autoocr <image-file>  
#

set -x

# If the TESSLANG variable is set use it, otherwise default to German language pack.
TESSLANG=${TESSLANG:-deu}

FILE="$1"

[ -r "$FILE" ] || exit 1

tesseract -l $TESSLANG  "$FILE" "$FILE" 

if [ "$?" != "0" ] 
then
	echo "tesseract OCR for file '$FILE' failed with exit code '$?'."
	exit 1
fi

